enum FileType {
    INE_FRONT = 'INE_FRONT',
    INE_BACK = 'INE_BACK',
    PASSPORT_FRONT = 'PASSPORT_FRONT',
    PASSPORT_BACK = 'PASSPORT_BACK',
    SIGNATURE = 'SIGNATURE',

    LEGAL_EXISTENCE = 'LEGAL_EXISTENCE', // EXISTENCIA LEGAL
    IDENTIFICATION_CARD = 'IDENTIFICATION_CARD', // Cedula CEDULA DE IDENTIFICACIÓN
    CONSTANCY_FIEL = 'CONSTANCY_FIEL', // CONSTANCIA DE FIRMA ELECTRÓNICA
    PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS', // COMPROBANTE DE DOMICILIO
    POWERS_OF_REPRESENTATIVES = 'POWERS_OF_REPRESENTATIVES', // PODERES DE REPRESENTANTES
    ID_REPRESENTATIVES = 'ID_REPRESENTATIVES',
}
export default FileType;
