enum Role {
    PERSONA_FISICA = 'PERSONA_FISICA',
    PERSONA_MORAL = 'PERSONA_MORAL',
    ADMIN = 'ADMIN',
    EXCHANGE_RATE = 'EXCHANGE_RATE',
    DOCUMENT_VALIDATOR = 'DOCUMENT_VALIDATOR',
}
export default Role;
